---
- name: Playbook para instalar la pila LAMP en el Backend
  hosts: backend
  become: yes

  vars_files:
    - ../vars/variables.yml
  tasks:

    - name: Instalamos el gestor de paquetes de Python pip3
      apt: 
        name: python3-pip
        state: present

    - name: Instalamos el módulo de pymysql
      pip:
        name: pymysql
        state: present

    - name: Crear una base de datos
      mysql_db:
        name: "{{ Wordpress.WORDPRESS_DB_NAME }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 

    - name: Crear el usuario de la base de datos
      no_log: true
      mysql_user:         
        name: "{{ Wordpress.WORDPRESS_DB_USER }}"
        password: "{{ Wordpress.WORDPRESS_DB_PASSWORD }}"
        priv: "{{ Wordpress.WORDPRESS_DB_NAME }}.*:ALL"
        host: "{{ Wordpress.IP_CLIENTE_MYSQL }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 